# Generated by Django 5.2.6 on 2025-09-05 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('link_post_marketer', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram_official', 'Instagram Official')], max_length=50)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_onboard_xendit', models.BooleanField(blank=True, null=True)),
                ('progressive_catalog_error', models.CharField(blank=True, max_length=255, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Trang',
                'verbose_name_plural': 'Trang',
                'db_table': 'pages',
                'unique_together': {('shop', 'pancake_id')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake_id', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('lighten_color', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_lead_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='shops.page')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'unique_together': {('page', 'pancake_id')},
            },
        ),
    ]
