# Generated by Django 5.2.6 on 2025-09-05 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('key_value', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Trường variation',
                'verbose_name_plural': 'Trường variation',
                'db_table': 'product_variation_fields',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake_id', models.CharField(max_length=100)),
                ('display_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('note_product', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('manipulation_warehouses', models.JSONField(blank=True, default=list)),
                ('inserted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='shops.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'products',
                'unique_together': {('shop', 'pancake_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('shops', 'Shops'), ('pages', 'Pages'), ('tags', 'Tags'), ('categories', 'Categories'), ('products', 'Products'), ('variations', 'Product Variations')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('created_records', models.IntegerField(default=0)),
                ('updated_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_histories', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Lịch sử đồng bộ',
                'verbose_name_plural': 'Lịch sử đồng bộ',
                'db_table': 'sync_histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake_id', models.CharField(max_length=100)),
                ('display_id', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retail_price_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price_at_counter', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_imported_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wholesale_price', models.JSONField(blank=True, default=list)),
                ('remain_quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_composite', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(blank=True, null=True)),
                ('is_sell_negative_variation', models.BooleanField(default=False)),
                ('images', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('composite_products', models.JSONField(blank=True, default=list)),
                ('bonus_variations', models.JSONField(blank=True, default=list)),
                ('variations_warehouses', models.JSONField(blank=True, default=list)),
                ('inserted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='shops.product')),
                ('fields', models.ManyToManyField(blank=True, related_name='variations', to='shops.productvariationfield')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'db_table': 'product_variations',
                'unique_together': {('product', 'pancake_id')},
            },
        ),
    ]
