# Generated by Django 5.2.6 on 2025-09-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_productvariationfield_product_synchistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='is_removed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
