# Generated by Django 5.2.6 on 2025-09-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_productvariation_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='is_composite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
