# Generated by Django 5.2.6 on 2025-09-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_user_alter_synchistory_sync_type_alter_tag_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='commune_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='commune_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderwarehouse',
            name='commune_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
