# Generated by Django 5.2.6 on 2025-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_customeraddress_commune_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchistory',
            name='sync_type',
            field=models.CharField(choices=[('shops', 'Shops'), ('pages', 'Pages'), ('tags', 'Tags'), ('categories', 'Categories'), ('products', 'Products'), ('variations', 'Product Variations'), ('customers', 'Customers'), ('users', 'Users'), ('orders', 'Orders')], max_length=50),
        ),
    ]
