# Generated by Django 5.2.6 on 2025-09-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_synchistory_sync_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('shop', 'pancake_id')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['referral_code'], name='customers_referra_0f0aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'customer_id'], name='customers_shop_id_258e62_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['fb_id'], name='customers_fb_id_ce4494_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
