# Generated by Django 5.2.6 on 2025-09-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Mới'), (17, 'Chờ xác nhận'), (11, 'Chờ hàng'), (12, 'Chờ in'), (13, 'Đã in'), (20, 'Đã đặt hàng'), (1, 'Đã xác nhận'), (8, 'Đang đóng hàng'), (9, 'Chờ chuyển hàng'), (2, 'Đã gửi hàng'), (3, 'Đã nhận'), (16, 'Đã thu tiền'), (4, 'Đang hoàn'), (15, 'Hoàn một phần'), (5, 'Đã hoàn'), (6, 'Đã hủy'), (7, 'Đã xóa')], default=0),
        ),
    ]
